blogsite/blog/urls.py
from django.urls import path, re_path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('instagram/', views.insta_view, name='insta_posts'),
    path(r'tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path(r'<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path(r'<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed')
]

blogsite/blogsite/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.contrib.sitemaps.views import sitemap as sitemap_view
from blog.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap_view, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blogsite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    tags = TaggableManager(verbose_name="Тэги")

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:post_detail', args=[self.publish.year, self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'), self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return "Комментарий сделан {} под {}".format(self.name, self.post)

blogsite/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blogsite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from  django.db.models import Count


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            comment_form = comment_form.cleaned_data
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by("-same_tags", "-publish")[:4]
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form, 'similar_posts': similar_posts})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    form = EmailPostForm(request.POST)

    if request.method == "POST":
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = "{} ({}) рекомендую к прочтению'{} '".format(cd['name'], cd['email'], post.title)
            message = "Читай {} на {}{} твои комменты: {}".format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, "noreply@nastassiablog.com", [cd['to']])
            sent = True
        else:
            form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def insta_view(request):
    return render(request, 'blog/post/insta.html')

blogsite/blog/templates/blog/base.html
{% load blog_tags %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!--<link href="{% static 'css/blog.css' %}" rel='stylesheet'>-->
</head>
<body>
    <div id="'content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>Мой блог</h2>
        <p>Это мой блог.Уже написано {% total_posts %} постов за все время.</p>
        <p><a href="{% url 'blog:post_feed'%}"> Подписаться на RSS ленту</a> </p>
        <h3>Последние записи </h3>
        {% show_latest_posts 3 %}

        <h3>Наиболее обсуждаемые записи </h3>
        {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>

    </div>
</body>
</html>

blogsite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="post-date">
        Опубликовано: {{ post.publish }}
        Автор: {{ post.author }}
    </p>

    {{ post.body|markdown }}
<p>
    <a href="{% url 'blog:post_share' post.id %}">
        Поделиться постом
    </a>
</p>
    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} комментариев
        </h2>
    {% endwith %}

    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    Похожих постов нет:(
    {% endfor %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Комментрий {{ forloop.counter }} сделан: {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}

    {% empty %}
    <p>Здесь пока нет комментариев, но вы можете оставить первый.</p>
</div>
{% endfor %}
{% if new_comment %}
<h2>Ваш комментарий был добавлен </h2>
{% else %}
<h2>Добавить новый комментарий </h2>
<form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Добавить комментарий"></p>
</form>
{% endif %}

{% endblock %}

blogsite/blog/templates/blog/post/insta.html
{% load instagram_client %}

{% instagram_user_recent_media littledorrit23 %}

<div id="django_recent_media_wall">
  {% for media in recent_media %}
    <div class="django_instagram_media_wall_item">
      <a href="{{ media.display_src }}" target="_blank" title="{{ media.caption }}">
        <img src="{{ media.thumbnail_src }}"/>
        <span>{{ media.caption }}</span>
      </a>
    </div>
  {% endfor %}
</div>

<h1>Instagram sliding box</h1>
{% instagram_recent_media_box usename="littledorrit23" %}

blogsite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blogsite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Мой блог{% endblock %}

{% block content %}
 {% include "pagination.html" with page=posts %}
<h1>Мой блог</h1>

    {% if  tag %}
        <h2> Посты с тегом "{{  tag.name }}"</h2>
    {% endif %}


  {% for post in posts %}
    <h2>
        <a href="{{ post.get_absolute_url }}">{{post.title}}</a>
    </h2>
        <p class="tags"> Тэги:
            {% for tag in post.tags.all %}
                <a href='{% url "blog:post_list_by_tag" tag.slug %}'> {{ tag.name }} </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>

    <p class="date">
        Опубликовано: {{ post.publish }}
        Автор: {{ post.author }}
    </p>
        {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}

{% endblock %}

blogsite/blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Поделиться постом{% endblock %}

{% block content %}
{% if sent %}
<h1> E-mail успешно отправлен</h1>
<p>
    "{{ post.title }}" был успешно отправлен {{ cd.to }}
</p>
{% else %}
<h1> Отправить "{{ post.title }}" на емейл </h1>
<form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Отправить e-mail">
</form>
{% endif %}
    {% endblock %}

blogsite/blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{page.previous_page_number}}">Предыдущая</a>
        {% endif %}
        <span class="current">
        Страница {{ page.number }} из {{ page.paginator.num_pages}}
        </span>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">Следующая</a>
        {% endif %}
    </span>

</div>